### ISSUE TITLE
Install spi_serial direct from Github with pip

### ISSUE THREAD

**Issue by scottleibrand** [EnhancedRadioDevices/915MHzEdisonExplorer_SW#11]
I would like to install spi_serial directly from Github with pip in OpenAPS, rather than having to clone the repo and `pip install -e .` locally, as we've been doing: (https://github.com/openaps/oref0/blob/master/bin/oref0-setup.sh#L305).  However, I was unable to do so because spi_serial is not at the root of the repo, but rather is a directory inside the 915MHzEdisonExplorer_SW repo.  As a workaround, I created my own repo just for spi_serial, and was able to install from there (https://github.com/openaps/oref0/blob/dev/bin/oref0-setup.sh#L482).

Is there a better way to get spi_serial installed with `pip` without having to clone the repo and maintain a local copy?  Or should we make spi_serial its own repo under EnhancedRadioDevices like I did?

**Comment by mogar** [comment]
I think we should definitely make spi_serial into its own repo. The original file-structure for this repo wasn't very well though out.

I'm thinking we create a new repo for spi_serial and rearrange the files in this repo there. I don't think there's anything in this repo that doesn't belong there. We can just move the examples directory into the spi_serial directory and use that as the root. Does that make sense?

**Comment by scottleibrand** [comment]
That works for me. Thanks.

**Comment by mogar** [comment]
We've created a new repo that we'll be transitioning to.

https://github.com/EnhancedRadioDevices/spi_serial
