### ISSUE TITLE
Bit-bang subg_rfspy programmer for 915MHz Edison Explorer board

### ISSUE THREAD

**Issue by scottleibrand** [EnhancedRadioDevices/915MHzEdisonExplorer_SW#3]
FYI, per https://gitter.im/nightscout/intend-to-bolus?at=57da1517fa660dd95fdf8bc5 @ps2 got a crude cc1110 bit banging programmer working today.  He says it should work on the explorer board as well, with some pin assignments changed, at https://github.com/ps2/riled_up_tools/blob/master/ccprog/ccprog.c#L11-L13

He says that when he gets this wrapped up into a more convenient command line util he can add a switch for the board.

Until then, documenting here in case anyone wants to try using it as-is.

**Comment by mogar** [comment]
@ps2 got this working with his ccprog repo, so I'm going to close this.
