### ISSUE TITLE
Making the code use more common python conventions and making it explorer specific

### ISSUE THREAD

**Issue by oskarpearson** [EnhancedRadioDevices/915MHzEdisonExplorer_SW#5]
I was wondering if you'd object to me renaming some of the files and libraries in a pull request?
- The current name spi_serial is possibly too generic - since it has some assumptions about GPIO ports and similar that are Edison Explorer specific.
- Some of the filenames (like RemoteLEDs.py) don't follow the normal python convention of lowercase filenames.
- I'd also like to add a software license to the README. Would you let me know which one you're releasing this under?

Once this is done, we can then push this as an actual Python package, which would make maintenance and installation easier.

Thanks!

**Comment by mogar** [comment]
That would be awesome. We're planning to use the MIT license, and I'd be
very grateful for the help in making this library conform to python's
styles.
